routes/web.php
<?php

use BaconQrCode\Encoder\QrCode;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\QrCodeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/login', function () {
//     return view('auth/login');
// });

Route::get('/', function () {
    return view('landingpage');
});

// Route::middleware('guest')->group(function);

Route::name('superadmin.')->middleware('superadmin')->group(function () {
    // Route::get('/superadmin', [HomeController::class, 'superadminhome'])->name('home');
    // Route::get('/list-admin', [AdminController::class, 'index'])->name('list-admin');
    // Route::get('/create-admin', [AdminController::class, 'create'])->name('create-admin');
    // Route::post('/store-admin', [AdminController::class, 'store'])->name('store-admin');
    Route::get('/superadmin', function () {
        return view('superadmin.superadminHome');
    })->name('home');

    Route::get('/addAdmin', [SuperAdminController::class, 'index'])->name('addAdmin');
    Route::get('/deleteAdmin/{id}', [SuperAdminController::class, 'delete'])->name('deleteAdmin');
    Route::get('/listUser', [SuperAdminController::class, 'indexUser'])->name('listUser');
});

Route::name('admin.')->middleware('admin')->group(function () {
    //admin home
    Route::get('/admin', [AdminController::class, 'indexAdmin'])->name('home');
    Route::get('/adminTransaction', [AdminController::class, 'transaction'])->name('admin-transaction');
    Route::get('/approved/{id_admin}/{id_order}', [AdminController::class, 'approved'])->name('approved');

    Route::get('/listUser', [SuperAdminController::class, 'indexUser'])->name('listUser');

    // Notifikasi
    Route::get('/read-notifikasi', [NotificationController::class, 'read'])->name('read-notifikasi');
    Route::get('/create-notifikasi', [NotificationController::class, 'create'])->name('create-notifikasi');;
    Route::post('/store-notifikasi', [NotificationController::class, 'store'])->name('store-notifikasi');
    Route::get('/jumlah-notifikasi', [NotificationController::class, 'jumlahNotif'])->name('jumlah-notifikasi');
    Route::get('/admin-getnotifpop', [NotificationController::class, 'getNotifPop'])->name('admin-getNotifPop');
    Route::get('/bacaNotif/{id}', [NotificationController::class, 'bacaNotif'])->name('bacaNotif');


    // QrCode
    Route::get('/create-qrcode', [QrCodeController::class, 'create'])->name('create-qrcode');
    Route::post('/store-qrcode', [QrCodeController::class, 'store'])->name('store-qrcode');


    // Route::get('/adminTransaction', function () {
    //     return view('admin.adminTransaction');
    // })->name('addAdmin');
});

Route::name('user.')->middleware('user')->group(function () {
    // user home
    Route::get('/user', [UserController::class, 'notification'])->name('home');
    Route::get('/userCart', [UserController::class, 'cart'])->name('userCart');
    Route::get('/userCheckout', [UserController::class, 'checkout'])->name('userCheckout');
    Route::post('/userCheckout/{id}', [UserController::class, 'orderNow'])->name('orderNow');
    // Route::get('/userCheckout', [UserController::class, 'checkout'])->name('userCheckout');


    // Notifikasi
    // Route::get('/userHome', [App\Http\Controllers\NotificationController::class, 'index'])->name('userHome');
    Route::post('/userHome', [NotificationController::class, 'store']);
    Route::get('/read-notifikasi', [NotificationController::class, 'read'])->name('read-notifikasi');
    Route::get('/jumlah-notifikasi', [NotificationController::class, 'jumlahNotif'])->name('jumlah-notifikasi');
    Route::get('/bacaNotif/{id}', [NotificationController::class, 'bacaNotif'])->name('bacaNotif');
    Route::get('/user-getnotifpop', [NotificationController::class, 'getNotifPop'])->name('user-getNotifPop');

    // Route::get('/notifikasi', [NotificationController::class, 'index'])->name('notifikasi');
    // Route::get('/user/profile', function () {
    //     // Uses first & second middleware...
    // });
});


Auth::routes(['verify' => true]);

// Home admin
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




// Chart
Route::get('/chart', [App\Http\Controllers\ChartController::class, 'index']);

resources/views/admin/adminTransaction.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-4">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary align-right">Data Transaction</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0"
                                    role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th>Customer</th>
                                            <th>Order</th>
                                            <th>Total</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach ($orders as $item)
                                            <tr>
                                                <td>{{ $item->user->name }}</td>
                                                <td>
                                                    @foreach ($item->detail as $detail)
                                                        {{ "{$detail->product->nama} x{$detail->jumlah}" }} <br>
                                                    @endforeach
                                                </td>
                                                <td>{{ "Rp. {$item->total}" }}</td>
                                                <td><a href="{{ route('admin.approved', ['id_admin' => Auth::id(), 'id_order' => $item->id]) }}"
                                                        class="btn btn-success btn-sm active ok" role="button"
                                                        aria-pressed="true"><i class="fa-solid fa-check">Approved</i></a>
                                                </td>
                                            </tr>
                                        @endforeach
                                        {{-- <form action="" method="post">
                                            <td>user 1</td>
                                            <td>ventela high</td>
                                            <td>1pcs</td>
                                            <td>Rp. 300.000</td>
                                            <td> <button type="submit">Approved</button></td>
                                        </form>

                                        @forelse ($orders as $order)
                                            <tr>
                                                <td>
                                                    <span class="font-weight-bold">{{ $order->customer->nama }}</span>
                                                </td>
                                                <td>
                                                    @foreach ($order->detail as $detail)
                                                        {{ $detail->product->nama }} Qty : {{ $detail->jumlah }} <br>
                                                    @endforeach
                                                </td>
                                                <td>@currency($order->total)</td>
                                                <td>
                                                    @if ($order->is_success === 0)
                                                        <a class="text-success approve"
                                                            href="{{ route('admin.approve', ['id_admin' => Auth::id(), 'id_order' => $order->id]) }}">
                                                            <i data-feather="check" width="14" height="14"></i>
                                                            <span>Approve</span>
                                                        </a>
                                                    @else
                                                        <span class="text-success font-weight-bold"><i data-feather="check"
                                                                width="14" height="14"></i> Approved</span>
                                                    @endif
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="4" class="text-center">DATA TIDAK DITEMUKAN !!</td>
                                            </tr>
                                        @endforelse --}}

                                        {{-- @foreach ($qrcodes as $item)
                                        <tr>

                                            <td>{{ QrCode::size(200)->generate($item->qrcode) }}</td>
                                            <td>{{ $item->qrcode }}</td>
                                            <td><a href="data:image/png;base64, {{ base64_encode(QrCode::format('png')->size(300)->generate($qrcode)) }}"
                                                    download="qrcode"><button type="download"
                                                        class="btn btn-primary">Download</button></a></a>
                                            </td>
                                        </tr>
                                    @endforeach --}}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form id="approve" method="POST" action="#">
        @csrf
        @method('POST')
    </form>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable();
        });
    </script>

    {{-- sweet alert --}}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.26/dist/sweetalert2.all.min.js"></script>
    <script>
        var ok = document.getElementsByClassName("ok");
        for (var i = 0; i < ok.length; i++) {
            ok[i].addEventListener('click', function(e) {
                e.preventDefault();
                var tujuan = this.href;
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#28a745',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, Approved Now!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = (tujuan);
                        Swal.fire({
                            title: 'Action Success!',
                            html: 'Your action has been success.',
                            icon: 'success',
                            showConfirmButton: false,
                        });
                    }
                })

            });
        }
    </script>
@endsection