routes/web.php
<?php

use BaconQrCode\Encoder\QrCode;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\QrCodeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/login', function () {
//     return view('auth/login');
// });

Route::get('/', function () {
    return view('landingpage');
});

// Route::middleware('guest')->group(function);

Route::name('superadmin.')->middleware('superadmin')->group(function () {
    // Route::get('/superadmin', [HomeController::class, 'superadminhome'])->name('home');
    // Route::get('/list-admin', [AdminController::class, 'index'])->name('list-admin');
    // Route::get('/create-admin', [AdminController::class, 'create'])->name('create-admin');
    // Route::post('/store-admin', [AdminController::class, 'store'])->name('store-admin');
    Route::get('/superadmin', function () {
        return view('superadmin.superadminHome');
    })->name('home');

    Route::get('/addAdmin', [SuperAdminController::class, 'index'])->name('addAdmin');
    Route::get('/deleteAdmin/{id}', [SuperAdminController::class, 'delete'])->name('deleteAdmin');
    Route::get('/listUser', [SuperAdminController::class, 'indexUser'])->name('listUser');
});

Route::name('admin.')->middleware('admin')->group(function () {
    //admin home
    Route::get('/admin', [AdminController::class, 'indexAdmin'])->name('home');
    Route::get('/adminTransaction', [AdminController::class, 'transaction'])->name('admin-transaction');
    Route::get('/approved/{id_admin}/{id_order}', [AdminController::class, 'approved'])->name('approved');

    Route::get('/listUser', [SuperAdminController::class, 'indexUser'])->name('listUser');

    // Notifikasi
    Route::get('/read-notifikasi', [NotificationController::class, 'read'])->name('read-notifikasi');
    Route::get('/create-notifikasi', [NotificationController::class, 'create'])->name('create-notifikasi');;
    Route::post('/store-notifikasi', [NotificationController::class, 'store'])->name('store-notifikasi');
    Route::get('/jumlah-notifikasi', [NotificationController::class, 'jumlahNotif'])->name('jumlah-notifikasi');
    Route::get('/admin-getnotifpop', [NotificationController::class, 'getNotifPop'])->name('admin-getNotifPop');
    Route::get('/bacaNotif/{id}', [NotificationController::class, 'bacaNotif'])->name('bacaNotif');


    // QrCode
    Route::get('/create-qrcode', [QrCodeController::class, 'create'])->name('create-qrcode');
    Route::post('/store-qrcode', [QrCodeController::class, 'store'])->name('store-qrcode');


    // Route::get('/adminTransaction', function () {
    //     return view('admin.adminTransaction');
    // })->name('addAdmin');
});

Route::name('user.')->middleware('user')->group(function () {
    // user home
    Route::get('/user', [UserController::class, 'notification'])->name('home');
    Route::get('/userCart', [UserController::class, 'cart'])->name('userCart');
    Route::get('/userCheckout', [UserController::class, 'checkout'])->name('userCheckout');
    Route::post('/userCheckout/{id}', [UserController::class, 'orderNow'])->name('orderNow');
    // Route::get('/userCheckout', [UserController::class, 'checkout'])->name('userCheckout');


    // Notifikasi
    // Route::get('/userHome', [App\Http\Controllers\NotificationController::class, 'index'])->name('userHome');
    Route::post('/userHome', [NotificationController::class, 'store']);
    Route::get('/read-notifikasi', [NotificationController::class, 'read'])->name('read-notifikasi');
    Route::get('/jumlah-notifikasi', [NotificationController::class, 'jumlahNotif'])->name('jumlah-notifikasi');
    Route::get('/bacaNotif/{id}', [NotificationController::class, 'bacaNotif'])->name('bacaNotif');
    Route::get('/user-getnotifpop', [NotificationController::class, 'getNotifPop'])->name('user-getNotifPop');

    // Route::get('/notifikasi', [NotificationController::class, 'index'])->name('notifikasi');
    // Route::get('/user/profile', function () {
    //     // Uses first & second middleware...
    // });
});


Auth::routes(['verify' => true]);

// Home admin
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




// Chart
Route::get('/chart', [App\Http\Controllers\ChartController::class, 'index']);

app/Http/Controllers/SuperAdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserNotification;
use Illuminate\Http\Request;


class SuperAdminController extends Controller
{
    public function index()
    {
        $admins = User::where('id_role', 2)->get();

        return view('superadmin.addAdmin', [
            'data_admins' => $admins,
            'data_notifications' => $this->alertnotif
        ]);
    }

    public function indexUser()
    {
        $users = User::where('id_role', 3)->get();

        return view('superadmin.listUser', [
            'data_users' => $users,
            'data_notifications' => $this->alertnotif
        ]);
    }

    public function delete($id)
    {
        $admin = User::find($id);

        $admin->delete();

        return back();
    }

    public function __construct()
    {
        $this->alertnotif = UserNotification::latest()->take(5)->get();
    }

    protected $alertnotif;
}

resources/views/superadmin/addAdmin.blade.php
@extends('layouts.app')

@section('style')
    <!-- Custom styles for this page -->
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-2 text-gray-800">List Admin</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fa-solid fa-plus mr-2" aria-hidden="true"></i>Add Admin</a>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary align-right">List Admin</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nama Admin</th>
                                <th>Nama Toko</th>
                                <th>Email</th>
                                <th>Alamat</th>
                                <th>No. Telp</th>
                                <th>Dibuat Tanggal</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data_admins as $item)
                                <tr>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->store_name }}</td>
                                    <td>{{ $item->email }}</td>
                                    <td>{{ $item->address }}</td>
                                    <td>{{ $item->phone }}</td>
                                    <td>{{ $item->created_at->format('d F Y') }}</td>
                                    <td>{{ $item->status }}</td>
                                    <td><a href="#" class="btn btn-primary btn-sm active  " role="button"
                                            aria-pressed="true"><i class="fa-solid fa-pen-to-square"></i></a>
                                        <a href="{{ route('superadmin.deleteAdmin', ['id' => $item->id]) }}"
                                            class="btn btn-danger btn-sm active  " role="button" aria-pressed="true"><i
                                                class="fa-solid fa-trash"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
    <!-- /.container-fluid -->
@endsection
@section('script')
    <!-- Page level custom scripts -->
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable();
        });
    </script>
@endsection

resources/views/superadmin/listUser.blade.php
@extends('layouts.app')

@section('style')
    <!-- Custom styles for this page -->
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/sweetalert2@7.12.15/dist/sweetalert2.min.css'>
@endsection

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-2 text-gray-800">List User</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm ok"><i
                    class="fa-solid fa-plus mr-2" aria-hidden="true"></i>Add User</a>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary align-right">List User</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nama User</th>
                                {{-- <th>Nama Toko</th> --}}
                                <th>Email</th>
                                <th>Jenis Kelamin</th>
                                <th>Alamat</th>
                                <th>No. Telp</th>
                                <th>Dibuat Tanggal</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data_users as $item)
                                <tr>
                                    <td>{{ $item->name }}</td>
                                    {{-- <td>{{ $item->store_name }}</td> --}}
                                    <td>{{ $item->email }}</td>
                                    <td>
                                        @if ($item->gender == 1)
                                            {{ 'Laki laki' }}
                                        @else
                                            {{ 'Perempuan' }}
                                        @endif
                                    </td>
                                    <td>{{ $item->address }}</td>
                                    <td>{{ $item->phone }}</td>
                                    <td>{{ $item->created_at->format('d F Y') }}</td>
                                    <td>{{ $item->status }}</td>
                                    <td><a href="#" class="btn btn-primary btn-sm active" role="button"
                                            aria-pressed="true"><i class="fa-solid fa-pen-to-square"></i></a>
                                        <a href="{{ route('superadmin.deleteAdmin', ['id' => $item->id]) }}"
                                            class="btn btn-danger btn-sm active ok " role="button" aria-pressed="true"><i
                                                class="fa-solid fa-trash"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection
@section('script')
    <!-- Page level custom scripts -->
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable();
        });
    </script>

    {{-- sweet alert --}}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.26/dist/sweetalert2.all.min.js"></script>
    <script>
        var ok = document.getElementsByClassName("ok");
        for (var i = 0; i < ok.length; i++) {
            ok[i].addEventListener('click', function(e) {
                e.preventDefault();
                var tujuan = this.href;
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, Delete Now!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = (tujuan);
                        Swal.fire({
                            title: 'Action Success!',
                            html: 'Your action has been success.',
                            icon: 'success',
                            showConfirmButton: false,
                        });
                    }
                })

            });
        }
    </script>
@endsection